[package]
name = "xppen-act05"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enumset = "1.1.3"
evdev = "0.12.2"
hidapi = "2.6.1"
serde = "1.0.203"
toml = "0.8.13"
